# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Logan Hsiao
title: Senior Software Engineer
email: jhsiao1121@gmail.com
website: github.com/jhsiao21

# Social links
#twitter_username: facespics
github_username:  jhsiao21
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: loganhsiao
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Logan and I'm a senior software engineer. As Foxconn software engineer, I am responsible for developing and implementing software applications in one of the world's largest electronics manufacturers.


# Projects Section
# projects_title: Software Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: Skills
more_content: | # this will include new lines to allow paragraphs
  - Software: <I>(proficient)</I>: <mark>Python</mark>,  <mark>C#</mark> <I>(familiar)</I>: <mark>C/C++</mark>, <mark>Java</mark>, <mark>Matlab</mark>, <mark>SQL</mark>
  - Professional: <I>(proficient)</I>: <mark>Machine Learning</mark>, <mark>Image Processing</mark>  <I>(familiar)</I>: <mark>Data Compression</mark>

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
